name: fastapi-videojuegos

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app-videojuegos
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - fastapi-db-postgres
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:1234@fastapi-db-postgres:5432/videojuegosdb
  
  fastapi-db-postgres:
    image: postgres:16
    container_name: fastapi-db-postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: videojuegosdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: