name: fastapi-videojuegos

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app-videojuegos
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - fastapi-db
  
  fastapi-db:
    image: mysql
    container_name: fastapi-db-videojuegos
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: videojuegosdb
      MYSQL_USER: joel
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"